/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadorabasica;

/**
 *
 * @author theus
 */
public class CalculadoraBasicaa extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraBasicaa
     */
    public CalculadoraBasicaa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloTela = new javax.swing.JLabel();
        txtNum01 = new javax.swing.JTextField();
        txtNum02 = new javax.swing.JTextField();
        btnCalculoSoma = new javax.swing.JButton();
        btnCalculoSub = new javax.swing.JButton();
        btnCalculoDiv = new javax.swing.JButton();
        btnCalculoMult = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblResultadoCalculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTela.setText("Calculadora Básica");

        txtNum01.setText("1° Número");

        txtNum02.setText("2° Número");

        btnCalculoSoma.setText("+");
        btnCalculoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoSomaActionPerformed(evt);
            }
        });

        btnCalculoSub.setText("-");
        btnCalculoSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoSubActionPerformed(evt);
            }
        });

        btnCalculoDiv.setText("/");
        btnCalculoDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoDivActionPerformed(evt);
            }
        });

        btnCalculoMult.setText("*");
        btnCalculoMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoMultActionPerformed(evt);
            }
        });

        lblResultado.setText("Resultado:");

        lblResultadoCalculo.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnCalculoSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculoDiv))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lblTituloTela))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(txtNum01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCalculoSub)
                                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNum02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblResultadoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnCalculoMult)))))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTituloTela)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculoSoma)
                    .addComponent(btnCalculoSub)
                    .addComponent(btnCalculoDiv)
                    .addComponent(btnCalculoMult))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(lblResultadoCalculo))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoSomaActionPerformed
        // TODO add your handling code here:
        Double num01Convertido = Double.valueOf(txtNum01.getText());
        
        Double num02Convertido = Double.valueOf(txtNum02.getText());
        
        Double resultadoCalculo = num01Convertido + num02Convertido;
        
        lblResultadoCalculo.setText(resultadoCalculo.toString());
    }//GEN-LAST:event_btnCalculoSomaActionPerformed

    private void btnCalculoSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoSubActionPerformed
        // TODO add your handling code here:
        Double num01Convertido = Double.valueOf(txtNum01.getText());
        
        Double num02Convertido = Double.valueOf(txtNum02.getText());
        
        Double resultadoCalculo = num01Convertido - num02Convertido;
        
        lblResultadoCalculo.setText(resultadoCalculo.toString());
    }//GEN-LAST:event_btnCalculoSubActionPerformed

    private void btnCalculoMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoMultActionPerformed
        // TODO add your handling code here:
        Double num01Convertido = Double.valueOf(txtNum01.getText());
        
        Double num02Convertido = Double.valueOf(txtNum02.getText());
        
        Double resultadoCalculo = num01Convertido * num02Convertido;
        
        lblResultadoCalculo.setText(resultadoCalculo.toString());
    }//GEN-LAST:event_btnCalculoMultActionPerformed

    private void btnCalculoDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoDivActionPerformed
        // TODO add your handling code here:
        Double num01Convertido = Double.valueOf(txtNum01.getText());
        
        Double num02Convertido = Double.valueOf(txtNum02.getText());
        
        Double resultadoCalculo = num01Convertido / num02Convertido;
        
        lblResultadoCalculo.setText(resultadoCalculo.toString());
    }//GEN-LAST:event_btnCalculoDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasicaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasicaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasicaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasicaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBasicaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculoDiv;
    private javax.swing.JButton btnCalculoMult;
    private javax.swing.JButton btnCalculoSoma;
    private javax.swing.JButton btnCalculoSub;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblResultadoCalculo;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JTextField txtNum01;
    private javax.swing.JTextField txtNum02;
    // End of variables declaration//GEN-END:variables
}
